using System.Collections.Generic;

namespace EnsoulAbarca
{
    class ChampionSkinData
    {
        public static Dictionary<string, Dictionary<string, int>> Skins = new Dictionary<string, Dictionary<string, int>>()
        {
            { "Aatrox", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Justicar Aatrox", 1 },
                { "Mecha Aatrox", 2 },
                { "Sea Hunter Aatrox", 3 },
                { "Blood Moon Aatrox", 7 },
                { "Blood Moon Aatrox Prestige Edition", 8 },
                { "Victorious Aatrox", 9 },
                { "Odyssey Aatrox", 11 },
            }},
            { "Ahri", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dynasty Ahri", 1 },
                { "Midnight Ahri", 2 },
                { "Foxfire Ahri", 3 },
                { "Popstar Ahri", 4 },
                { "Challenger Ahri", 5 },
                { "Academy Ahri", 6 },
                { "Arcade Ahri", 7 },
                { "Star Guardian Ahri", 14 },
                { "K/DA Ahri", 15 },
                { "K/DA Ahri Prestige Edition", 16 },
                { "Elderwood Ahri", 17 },
                { "Spirit Blossom Ahri", 27 },
            }},
            { "Akali", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Stinger Akali", 1 },
                { "Infernal Akali", 2 },
                { "All-star Akali", 3 },
                { "Nurse Akali", 4 },
                { "Blood Moon Akali", 5 },
                { "Silverfang Akali", 6 },
                { "Headhunter Akali", 7 },
                { "Sashimi Akali", 8 },
                { "K/DA Akali", 9 },
                { "K/DA Akali Prestige Edition", 13 },
                { "PROJECT: Akali", 14 },
                { "True Damage Akali", 15 },
            }},
            { "Alistar", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Black Alistar", 1 },
                { "Golden Alistar", 2 },
                { "Matador Alistar", 3 },
                { "Longhorn Alistar", 4 },
                { "Unchained Alistar", 5 },
                { "Infernal Alistar", 6 },
                { "Sweeper Alistar", 7 },
                { "Marauder Alistar", 8 },
                { "SKT T1 Alistar", 9 },
                { "Moo Cow Alistar", 10 },
                { "Hextech Alistar", 19 },
                { "Conqueror Alistar", 20 },
                { "Blackfrost Alistar", 22 },
            }},
            { "Amumu", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Pharaoh Amumu", 1 },
                { "Vancouver Amumu", 2 },
                { "Emumu", 3 },
                { "Re-Gifted Amumu", 4 },
                { "Almost-Prom King Amumu", 5 },
                { "Little Knight Amumu", 6 },
                { "Sad Robot Amumu", 7 },
                { "Surprise Party Amumu", 8 },
                { "Infernal Amumu", 17 },
                { "Hextech Amumu", 23 },
                { "Pumpkin Prince Amumu", 24 },
            }},
            { "Anivia", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Team Spirit Anivia", 1 },
                { "Bird of Prey Anivia", 2 },
                { "Noxus Hunter Anivia", 3 },
                { "Hextech Anivia", 4 },
                { "Blackfrost Anivia", 5 },
                { "Prehistoric Anivia", 6 },
                { "Festival Queen Anivia", 7 },
                { "Papercraft Anivia", 8 },
            }},
            { "Annie", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Goth Annie", 1 },
                { "Red Riding Annie", 2 },
                { "Annie in Wonderland", 3 },
                { "Prom Queen Annie", 4 },
                { "Frostfire Annie", 5 },
                { "Reverse Annie", 6 },
                { "FrankenTibbers Annie", 7 },
                { "Panda Annie", 8 },
                { "Sweetheart Annie", 9 },
                { "Hextech Annie", 10 },
                { "Super Galaxy Annie", 11 },
                { "Annie-Versary", 12 },
            }},
            { "Aphelios", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Nightbringer Aphelios", 1 },
            }},
            { "Ashe", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Freljord Ashe", 1 },
                { "Sherwood Forest Ashe", 2 },
                { "Woad Ashe", 3 },
                { "Queen Ashe", 4 },
                { "Amethyst Ashe", 5 },
                { "Heartseeker Ashe", 6 },
                { "Marauder Ashe", 7 },
                { "PROJECT: Ashe", 8 },
                { "Championship Ashe", 9 },
                { "Cosmic Queen Ashe", 11 },
                { "High Noon Ashe", 17 },
                { "Fae Dragon Ashe", 23 },
            }},
            { "AurelionSol", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Ashen Lord Aurelion Sol", 1 },
                { "Mecha Aurelion Sol", 2 },
                { "Storm Dragon Aurelion Sol", 11 },
            }},
            { "Azir", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Galactic Azir", 1 },
                { "Gravelord Azir", 2 },
                { "SKT T1 Azir", 3 },
                { "Warring Kingdoms Azir", 4 },
            }},
            { "Bard", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Elderwood Bard", 1 },
                { "Snow Day Bard", 5 },
                { "Bard Bard", 6 },
                { "Astronaut Bard", 8 },
            }},
            { "Blitzcrank", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Rusty Blitzcrank", 1 },
                { "Goalkeeper Blitzcrank", 2 },
                { "Boom Boom Blitzcrank", 3 },
                { "Piltover Customs Blitzcrank", 4 },
                { "Definitely Not Blitzcrank", 5 },
                { "iBlitzcrank", 6 },
                { "Riot Blitzcrank", 7 },
                { "Battle Boss Blitzcrank", 11 },
                { "Lancer Rogue Blitzcrank", 20 },
                { "Lancer Paragon Blitzcrank", 21 },
                { "Witch's Brew Blitzcrank", 22 },
            }},
            { "Brand", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Apocalyptic Brand", 1 },
                { "Vandal Brand", 2 },
                { "Cryocore Brand", 3 },
                { "Zombie Brand", 4 },
                { "Spirit Fire Brand", 5 },
                { "Battle Boss Brand", 6 },
                { "Arclight Brand", 7 },
                { "Eternal Dragon Brand", 8 },
            }},
            { "Braum", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dragonslayer Braum", 1 },
                { "El Tigre Braum", 2 },
                { "Braum Lionheart", 3 },
                { "Santa Braum", 10 },
                { "Crime City Braum", 11 },
                { "Sugar Rush Braum", 24 },
            }},
            { "Caitlyn", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Resistance Caitlyn", 1 },
                { "Sheriff Caitlyn", 2 },
                { "Safari Caitlyn", 3 },
                { "Arctic Warfare Caitlyn", 4 },
                { "Officer Caitlyn", 5 },
                { "Headhunter Caitlyn", 6 },
                { "Lunar Wraith Caitlyn", 10 },
                { "Pulsefire Caitlyn", 11 },
                { "Pool Party Caitlyn", 13 },
                { "Arcade Caitlyn", 19 },
                { "Arcade Caitlyn Prestige Edition", 20 },
            }},
            { "Camille", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Program Camille", 1 },
                { "Coven Camille", 2 },
                { "iG Camille", 10 },
            }},
            { "Cassiopeia", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Desperada Cassiopeia", 1 },
                { "Siren Cassiopeia", 2 },
                { "Mythic Cassiopeia", 3 },
                { "Jade Fang Cassiopeia", 4 },
                { "Eternum Cassiopeia", 8 },
                { "Spirit Blossom Cassiopeia", 9 },
            }},
            { "Chogath", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Nightmare Cho'Gath", 1 },
                { "Gentleman Cho'Gath", 2 },
                { "Loch Ness Cho'Gath", 3 },
                { "Jurassic Cho'Gath", 4 },
                { "Battlecast Prime Cho'Gath", 5 },
                { "Prehistoric Cho'Gath", 6 },
                { "Dark Star Cho'Gath", 7 },
            }},
            { "Corki", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "UFO Corki", 1 },
                { "Ice Toboggan Corki", 2 },
                { "Red Baron Corki", 3 },
                { "Hot Rod Corki", 4 },
                { "Urfrider Corki", 5 },
                { "Dragonwing Corki", 6 },
                { "Fnatic Corki", 7 },
                { "Arcade Corki", 8 },
                { "Corgi Corki", 18 },
            }},
            { "Darius", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Lord Darius", 1 },
                { "Bioforge Darius", 2 },
                { "Woad King Darius", 3 },
                { "Dunkmaster Darius", 4 },
                { "Academy Darius", 8 },
                { "Dreadnova Darius", 14 },
                { "God-King Darius", 15 },
                { "High Noon Darius", 16 },
            }},
            { "Diana", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dark Valkyrie Diana", 1 },
                { "Lunar Goddess Diana", 2 },
                { "Infernal Diana", 3 },
                { "Blood Moon Diana", 11 },
                { "Dark Waters Diana", 12 },
                { "Dragonslayer Diana", 18 },
            }},
            { "Draven", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Soul Reaver Draven", 1 },
                { "Gladiator Draven", 2 },
                { "Primetime Draven", 3 },
                { "Pool Party Draven", 4 },
                { "Beast Hunter Draven", 5 },
                { "Draven Draven", 6 },
                { "Santa Draven", 12 },
                { "Mecha Kingdoms Draven", 13 },
            }},
            { "DrMundo", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Toxic Dr. Mundo", 1 },
                { "Mr. Mundoverse", 2 },
                { "Corporate Mundo", 3 },
                { "Mundo Mundo", 4 },
                { "Executioner Mundo", 5 },
                { "Rageborn Mundo", 6 },
                { "TPA Mundo", 7 },
                { "Pool Party Mundo", 8 },
                { "El Macho Mundo", 9 },
                { "Frozen Prince Mundo", 10 },
            }},
            { "Ekko", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sandstorm Ekko", 1 },
                { "Academy Ekko", 2 },
                { "PROJECT: Ekko", 3 },
                { "SKT T1 Ekko", 11 },
                { "Trick or Treat Ekko", 12 },
                { "True Damage Ekko", 19 },
                { "Pulsefire Ekko", 28 },
            }},
            { "Elise", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Death Blossom Elise", 1 },
                { "Victorious Elise", 2 },
                { "Blood Moon Elise", 3 },
                { "SKT T1 Elise", 4 },
                { "Super Galaxy Elise", 5 },
                { "Bewitching Elise", 6 },
            }},
            { "Evelynn", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Shadow Evelynn", 1 },
                { "Masquerade Evelynn", 2 },
                { "Tango Evelynn", 3 },
                { "Safecracker Evelynn", 4 },
                { "Blood Moon Evelynn", 5 },
                { "K/DA Evelynn", 6 },
                { "K/DA Evelynn Prestige Edition", 7 },
                { "Sugar Rush Evelynn", 8 },
            }},
            { "Ezreal", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Nottingham Ezreal", 1 },
                { "Striker Ezreal", 2 },
                { "Frosted Ezreal", 3 },
                { "Explorer Ezreal", 4 },
                { "Pulsefire Ezreal", 5 },
                { "TPA Ezreal", 6 },
                { "Debonair Ezreal", 7 },
                { "Ace of Spades Ezreal", 8 },
                { "Arcade Ezreal", 9 },
                { "Star Guardian Ezreal", 18 },
                { "SSG Ezreal", 19 },
                { "Pajama Guardian Ezreal", 20 },
                { "Battle Academia Ezreal", 21 },
                { "PsyOps Ezreal", 22 },
                { "PsyOps Ezreal Prestige Edition", 23 },
            }},
            { "Fiddlesticks", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Spectral Fiddlesticks", 1 },
                { "Union Jack Fiddlesticks", 2 },
                { "Bandito Fiddlesticks", 3 },
                { "Pumpkinhead Fiddlesticks", 4 },
                { "Fiddle Me Timbers", 5 },
                { "Surprise Party Fiddlesticks", 6 },
                { "Dark Candy Fiddlesticks", 7 },
                { "Risen Fiddlesticks", 8 },
                { "Praetorian Fiddlesticks", 9 },
            }},
            { "Fiora", new Dictionary<string, int> {
                { "default", 0 },
                { "Royal Guard Fiora", 1 },
                { "Nightraven Fiora", 2 },
                { "Headmistress Fiora", 3 },
                { "PROJECT: Fiora", 4 },
                { "Pool Party Fiora", 5 },
                { "Soaring Sword Fiora", 22 },
                { "Heartpiercer Fiora", 23 },
                { "iG Fiora", 31 },
                { "Pulsefire Fiora", 41 },
            }},
            { "Fizz", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Atlantean Fizz", 1 },
                { "Tundra Fizz", 2 },
                { "Fisherman Fizz", 3 },
                { "Void Fizz", 4 },
                { "Cottontail Fizz", 8 },
                { "Super Galaxy Fizz", 9 },
                { "Omega Squad Fizz", 10 },
                { "Fuzz Fizz", 14 },
                { "Fuzz Fizz Prestige Edition", 15 },
                { "Little Devil Fizz", 16 },
            }},
            { "Galio", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Enchanted Galio", 1 },
                { "Hextech Galio", 2 },
                { "Commando Galio", 3 },
                { "Gatekeeper Galio", 4 },
                { "Debonair Galio", 5 },
                { "Birdio", 6 },
                { "Infernal Galio", 13 },
            }},
            { "Gangplank", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Spooky Gangplank", 1 },
                { "Minuteman Gangplank", 2 },
                { "Sailor Gangplank", 3 },
                { "Toy Soldier Gangplank", 4 },
                { "Special Forces Gangplank", 5 },
                { "Sultan Gangplank", 6 },
                { "Captain Gangplank", 7 },
                { "Dreadnova Gangplank", 8 },
                { "Pool Party Gangplank", 14 },
                { "FPX Gangplank", 21 },
            }},
            { "Garen", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sanguine Garen", 1 },
                { "Desert Trooper Garen", 2 },
                { "Commando Garen", 3 },
                { "Dreadknight Garen", 4 },
                { "Rugged Garen", 5 },
                { "Steel Legion Garen", 6 },
                { "Rogue Admiral Garen", 10 },
                { "Warring Kingdoms Garen", 11 },
                { "God-King Garen", 13 },
                { "Demacia Vice Garen", 14 },
                { "Mecha Kingdoms Garen", 22 },
                { "Mecha Kingdoms Garen Prestige Edition", 23 },
            }},
            { "Gnar", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dino Gnar", 1 },
                { "Gentleman Gnar", 2 },
                { "Snow Day Gnar", 3 },
                { "El León Gnar", 4 },
                { "Super Galaxy Gnar", 13 },
                { "SSG Gnar", 14 },
                { "Astronaut Gnar", 15 },
            }},
            { "Gragas", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Scuba Gragas", 1 },
                { "Hillbilly Gragas", 2 },
                { "Santa Gragas", 3 },
                { "Gragas, Esq.", 4 },
                { "Vandal Gragas", 5 },
                { "Oktoberfest Gragas", 6 },
                { "Superfan Gragas", 7 },
                { "Fnatic Gragas", 8 },
                { "Gragas Caskbreaker", 9 },
                { "Arctic Ops Gragas", 10 },
            }},
            { "Graves", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Hired Gun Graves", 1 },
                { "Jailbreak Graves", 2 },
                { "Crime City Graves", 3 },
                { "Riot Graves", 4 },
                { "Pool Party Graves", 5 },
                { "Cutthroat Graves", 6 },
                { "Snow Day Graves", 7 },
                { "Victorious Graves", 14 },
                { "Praetorian Graves", 18 },
                { "Battle Professor Graves", 25 },
            }},
            { "Hecarim", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Blood Knight Hecarim", 1 },
                { "Reaper Hecarim", 2 },
                { "Headless Hecarim", 3 },
                { "Arcade Hecarim", 4 },
                { "Elderwood Hecarim", 5 },
                { "Worldbreaker Hecarim", 6 },
                { "Lancer Zero Hecarim", 7 },
                { "High Noon Hecarim", 8 },
            }},
            { "Heimerdinger", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Alien Invader Heimerdinger", 1 },
                { "Blast Zone Heimerdinger", 2 },
                { "Piltover Customs Heimerdinger", 3 },
                { "Snowmerdinger", 4 },
                { "Hazmat Heimerdinger", 5 },
                { "Dragon Trainer Heimerdinger", 6 },
                { "Pool Party Heimerdinger", 15 },
            }},
            { "Illaoi", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Void Bringer Illaoi", 1 },
                { "Resistance Illaoi", 2 },
            }},
            { "Irelia", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Nightblade Irelia", 1 },
                { "Aviator Irelia", 2 },
                { "Infiltrator Irelia", 3 },
                { "Frostblade Irelia", 4 },
                { "Order of the Lotus Irelia", 5 },
                { "Divine Sword Irelia", 6 },
                { "iG Irelia", 15 },
                { "PROJECT: Irelia", 16 },
                { "PROJECT: Irelia Prestige Edition", 17 },
                { "High Noon Irelia", 18 },
            }},
            { "Ivern", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Candy King Ivern", 1 },
                { "Dunkmaster Ivern", 2 },
            }},
            { "Janna", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Tempest Janna", 1 },
                { "Hextech Janna", 2 },
                { "Frost Queen Janna", 3 },
                { "Victorious Janna", 4 },
                { "Forecast Janna", 5 },
                { "Fnatic Janna", 6 },
                { "Star Guardian Janna", 7 },
                { "Sacred Sword Janna", 8 },
                { "Bewitching Janna", 13 },
                { "Guardian of the Sands Janna", 20 },
            }},
            { "JarvanIV", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Commando Jarvan IV", 1 },
                { "Dragonslayer Jarvan IV", 2 },
                { "Darkforge Jarvan IV", 3 },
                { "Victorious Jarvan IV", 4 },
                { "Warring Kingdoms Jarvan IV", 5 },
                { "Fnatic Jarvan IV", 6 },
                { "Dark Star Jarvan IV", 7 },
                { "SSG Jarvan IV", 8 },
                { "Hextech Jarvan IV", 9 },
                { "Pool Party Jarvan IV", 11 },
            }},
            { "Jax", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "The Mighty Jax", 1 },
                { "Vandal Jax", 2 },
                { "Angler Jax", 3 },
                { "PAX Jax", 4 },
                { "Jaximus", 5 },
                { "Temple Jax", 6 },
                { "Nemesis Jax", 7 },
                { "SKT T1 Jax", 8 },
                { "Warden Jax", 12 },
                { "God Staff Jax", 13 },
                { "Mecha Kingdoms Jax", 14 },
            }},
            { "Jayce", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Full Metal Jayce", 1 },
                { "Debonair Jayce", 2 },
                { "Forsaken Jayce", 3 },
                { "Jayce Brighthammer", 4 },
                { "Battle Academia Jayce", 5 },
            }},
            { "Jhin", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "High Noon Jhin", 1 },
                { "Blood Moon Jhin", 2 },
                { "SKT T1 Jhin", 3 },
                { "PROJECT: Jhin", 4 },
                { "Dark Cosmic Jhin", 5 },
            }},
            { "Jinx", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Crime City Jinx", 1 },
                { "Firecracker Jinx", 2 },
                { "Zombie Slayer Jinx", 3 },
                { "Star Guardian Jinx", 4 },
                { "Ambitious Elf Jinx", 12 },
                { "Odyssey Jinx", 13 },
                { "PROJECT: Jinx", 20 },
                { "Heartseeker Jinx", 29 },
            }},
            { "Kaisa", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Bullet Angel Kai'Sa", 1 },
                { "K/DA Kai'Sa", 14 },
                { "K/DA Kai'Sa Prestige Edition", 15 },
                { "iG Kai'Sa", 16 },
                { "Arcade Kai'Sa", 17 },
            }},
            { "Kalista", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Blood Moon Kalista", 1 },
                { "Championship Kalista", 2 },
                { "SKT T1 Kalista", 3 },
            }},
            { "Karma", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sun Goddess Karma", 1 },
                { "Sakura Karma", 2 },
                { "Traditional Karma", 3 },
                { "Order of the Lotus Karma", 4 },
                { "Warden Karma", 5 },
                { "Winter Wonder Karma", 6 },
                { "Conqueror Karma", 7 },
                { "Dark Star Karma", 8 },
                { "Dawnbringer Karma", 19 },
                { "Odyssey Karma", 26 },
            }},
            { "Karthus", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Phantom Karthus", 1 },
                { "Statue of Karthus", 2 },
                { "Grim Reaper Karthus", 3 },
                { "Pentakill Karthus", 4 },
                { "Fnatic Karthus", 5 },
                { "Karthus Lightsbane", 9 },
                { "Infernal Karthus", 10 },
            }},
            { "Kassadin", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Festival Kassadin", 1 },
                { "Deep One Kassadin", 2 },
                { "Pre-Void Kassadin", 3 },
                { "Harbinger Kassadin", 4 },
                { "Cosmic Reaver Kassadin", 5 },
                { "Count Kassadin", 6 },
                { "Hextech Kassadin", 14 },
            }},
            { "Katarina", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Mercenary Katarina", 1 },
                { "Red Card Katarina", 2 },
                { "Bilgewater Katarina", 3 },
                { "Kitty Cat Katarina", 4 },
                { "High Command Katarina", 5 },
                { "Sandstorm Katarina", 6 },
                { "Slay Belle Katarina", 7 },
                { "Warring Kingdoms Katarina", 8 },
                { "PROJECT: Katarina", 9 },
                { "Death Sworn Katarina", 10 },
                { "Battle Academia Katarina", 12 },
                { "Blood Moon Katarina", 21 },
            }},
            { "Kayle", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Silver Kayle", 1 },
                { "Viridian Kayle", 2 },
                { "Transcended Kayle", 3 },
                { "Battleborn Kayle", 4 },
                { "Judgment Kayle", 5 },
                { "Aether Wing Kayle", 6 },
                { "Riot Kayle", 7 },
                { "Iron Inquisitor Kayle", 8 },
                { "Pentakill Kayle", 9 },
                { "PsyOps Kayle", 15 },
            }},
            { "Kayn", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Soulhunter Kayn", 1 },
                { "Odyssey Kayn", 2 },
            }},
            { "Kennen", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Deadly Kennen", 1 },
                { "Swamp Master Kennen", 2 },
                { "Karate Kennen", 3 },
                { "Kennen M.D.", 4 },
                { "Arctic Ops Kennen", 5 },
                { "Blood Moon Kennen", 6 },
                { "Super Kennen", 7 },
                { "Infernal Kennen", 8 },
            }},
            { "Khazix", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Mecha Kha'Zix", 1 },
                { "Guardian of the Sands Kha'Zix", 2 },
                { "Death Blossom Kha'Zix", 3 },
                { "Dark Star Kha'Zix", 4 },
                { "Championship Kha'Zix", 11 },
                { "Odyssey Kha'Zix", 60 },
            }},
            { "Kindred", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Shadowfire Kindred", 1 },
                { "Super Galaxy Kindred", 2 },
                { "Spirit Blossom Kindred", 3 },
            }},
            { "Kled", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sir Kled", 1 },
                { "Count Kledula", 2 },
            }},
            { "KogMaw", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Caterpillar Kog'Maw", 1 },
                { "Sonoran Kog'Maw", 2 },
                { "Monarch Kog'Maw", 3 },
                { "Reindeer Kog'Maw", 4 },
                { "Lion Dance Kog'Maw", 5 },
                { "Deep Sea Kog'Maw", 6 },
                { "Jurassic Kog'Maw", 7 },
                { "Battlecast Kog'Maw", 8 },
                { "Pug'Maw", 9 },
                { "Hextech Kog'Maw", 10 },
                { "Arcanist Kog'Maw", 19 },
            }},
            { "Leblanc", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Wicked LeBlanc", 1 },
                { "Prestigious LeBlanc", 2 },
                { "Mistletoe LeBlanc", 3 },
                { "Ravenborn LeBlanc", 4 },
                { "Elderwood LeBlanc", 5 },
                { "Program LeBlanc", 12 },
                { "iG LeBlanc", 19 },
                { "Coven LeBlanc", 20 },
                { "Championship LeBlanc", 29 },
            }},
            { "LeeSin", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Traditional Lee Sin", 1 },
                { "Acolyte Lee Sin", 2 },
                { "Dragon Fist Lee Sin", 3 },
                { "Muay Thai Lee Sin", 4 },
                { "Pool Party Lee Sin", 5 },
                { "SKT T1 Lee Sin", 6 },
                { "Knockout Lee Sin", 10 },
                { "God Fist Lee Sin", 11 },
                { "Playmaker Lee Sin", 12 },
                { "Nightbringer Lee Sin", 27 },
                { "Nightbringer Lee Sin Prestige Edition", 28 },
                { "FPX Lee Sin", 29 },
                { "Storm Dragon Lee Sin", 31 },
            }},
            { "Leona", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Valkyrie Leona", 1 },
                { "Defender Leona", 2 },
                { "Iron Solari Leona", 3 },
                { "Pool Party Leona", 4 },
                { "PROJECT: Leona", 8 },
                { "Barbecue Leona", 9 },
                { "Solar Eclipse Leona", 10 },
                { "Lunar Eclipse Leona", 11 },
                { "Mecha Kingdoms Leona", 12 },
            }},
            { "Lillia", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Spirit Blossom Lillia", 1 },
            }},
            { "Lissandra", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Bloodstone Lissandra", 1 },
                { "Blade Queen Lissandra", 2 },
                { "Program Lissandra", 3 },
                { "Coven Lissandra", 4 },
            }},
            { "Lucian", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Hired Gun Lucian", 1 },
                { "Striker Lucian", 2 },
                { "PROJECT: Lucian", 6 },
                { "Heartseeker Lucian", 7 },
                { "High Noon Lucian", 8 },
                { "Demacia Vice Lucian", 9 },
                { "Pulsefire Lucian", 18 },
                { "Pulsefire Lucian Prestige Edition", 19 },
            }},
            { "Lulu", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Bittersweet Lulu", 1 },
                { "Wicked Lulu", 2 },
                { "Dragon Trainer Lulu", 3 },
                { "Winter Wonder Lulu", 4 },
                { "Pool Party Lulu", 5 },
                { "Star Guardian Lulu", 6 },
                { "Cosmic Enchantress Lulu", 14 },
                { "Pajama Guardian Lulu", 15 },
            }},
            { "Lux", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sorceress Lux", 1 },
                { "Spellthief Lux", 2 },
                { "Commando Lux", 3 },
                { "Imperial Lux", 4 },
                { "Steel Legion Lux", 5 },
                { "Star Guardian Lux", 6 },
                { "Elementalist Lux", 7 },
                { "Lunar Empress Lux", 8 },
                { "Pajama Guardian Lux", 14 },
                { "Battle Academia Lux", 15 },
                { "Battle Academia Lux Prestige Edition", 16 },
                { "Dark Cosmic Lux", 17 },
                { "Cosmic Lux", 18 },
            }},
            { "Malphite", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Shamrock Malphite", 1 },
                { "Coral Reef Malphite", 2 },
                { "Marble Malphite", 3 },
                { "Obsidian Malphite", 4 },
                { "Glacial Malphite", 5 },
                { "Mecha Malphite", 6 },
                { "Ironside Malphite", 7 },
                { "Odyssey Malphite", 16 },
                { "Dark Star Malphite", 23 },
                { "Dark Star Malphite Prestige Edition", 24 },
                { "FPX Malphite", 25 },
            }},
            { "Malzahar", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Vizier Malzahar", 1 },
                { "Shadow Prince Malzahar", 2 },
                { "Djinn Malzahar", 3 },
                { "Overlord Malzahar", 4 },
                { "Snow Day Malzahar", 5 },
                { "Battle Boss Malzahar", 6 },
                { "Hextech Malzahar", 7 },
                { "Worldbreaker Malzahar", 9 },
            }},
            { "Maokai", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Charred Maokai", 1 },
                { "Totemic Maokai", 2 },
                { "Festive Maokai", 3 },
                { "Haunted Maokai", 4 },
                { "Goalkeeper Maokai", 5 },
                { "Meowkai", 6 },
                { "Victorious Maokai", 7 },
                { "Worldbreaker Maokai", 16 },
            }},
            { "MasterYi", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Assassin Master Yi", 1 },
                { "Chosen Master Yi", 2 },
                { "Ionia Master Yi", 3 },
                { "Samurai Yi", 4 },
                { "Headhunter Master Yi", 5 },
                { "Skin 6", 6 },
                { "Skin 7", 7 },
                { "Skin 8", 8 },
                { "PROJECT: Yi", 9 },
                { "Cosmic Blade Master Yi", 10 },
                { "Eternal Sword Yi", 11 },
                { "Skin 12", 12 },
                { "Skin 13", 13 },
                { "Skin 14", 14 },
                { "Skin 15", 15 },
                { "Skin 16", 16 },
                { "Snow Man Yi", 17 },
                { "Skin 18", 18 },
                { "Skin 19", 19 },
                { "Skin 20", 20 },
                { "Skin 21", 21 },
                { "Skin 22", 22 },
                { "Skin 23", 23 },
                { "Blood Moon Master Yi", 24 },
                { "Skin 25", 25 },
                { "Skin 26", 26 },
                { "Skin 27", 27 },
                { "Skin 28", 28 },
                { "Skin 29", 29 },
                { "Skin 30", 30 },
                { "Skin 31", 31 },
                { "Skin 32", 32 },
                { "PsyOps Master Yi", 33 },
            }},
            { "MissFortune", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Cowgirl Miss Fortune", 1 },
                { "Waterloo Miss Fortune", 2 },
                { "Secret Agent Miss Fortune", 3 },
                { "Candy Cane Miss Fortune", 4 },
                { "Road Warrior Miss Fortune", 5 },
                { "Crime City Miss Fortune", 6 },
                { "Arcade Miss Fortune", 7 },
                { "Captain Fortune", 8 },
                { "Pool Party Miss Fortune", 9 },
                { "Star Guardian Miss Fortune", 15 },
                { "Gun Goddess Miss Fortune", 16 },
                { "Pajama Guardian Miss Fortune", 17 },
                { "Bewitching Miss Fortune ", 18 },
                { "Bewitching Miss Fortune Prestige Edition", 20 },
            }},
            { "MonkeyKing", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Volcanic Wukong", 1 },
                { "General Wukong", 2 },
                { "Jade Dragon Wukong", 3 },
                { "Underworld Wukong", 4 },
                { "Radiant Wukong", 5 },
                { "Lancer Stratus Wukong", 6 },
            }},
            { "Mordekaiser", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dragon Knight Mordekaiser", 1 },
                { "Infernal Mordekaiser", 2 },
                { "Pentakill Mordekaiser", 3 },
                { "Lord Mordekaiser", 4 },
                { "King of Clubs Mordekaiser", 5 },
                { "Dark Star Mordekaiser", 6 },
            }},
            { "Morgana", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Exiled Morgana", 1 },
                { "Sinful Succulence Morgana", 2 },
                { "Blade Mistress Morgana", 3 },
                { "Blackthorn Morgana", 4 },
                { "Ghost Bride Morgana", 5 },
                { "Victorious Morgana", 6 },
                { "Lunar Wraith Morgana", 10 },
                { "Bewitching Morgana", 11 },
                { "Majestic Empress Morgana", 17 },
                { "Coven Morgana", 26 },
            }},
            { "Nami", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Koi Nami", 1 },
                { "River Spirit Nami", 2 },
                { "Urf the Nami-tee", 3 },
                { "Deep Sea Nami", 7 },
                { "SKT T1 Nami", 8 },
                { "Program Nami", 9 },
                { "Splendid Staff Nami", 15 },
            }},
            { "Nasus", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Galactic Nasus", 1 },
                { "Pharaoh Nasus", 2 },
                { "Dreadknight Nasus", 3 },
                { "Riot K-9 Nasus", 4 },
                { "Infernal Nasus", 5 },
                { "Archduke Nasus", 6 },
                { "Worldbreaker Nasus", 10 },
                { "Lunar Guardian Nasus", 11 },
            }},
            { "Nautilus", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Abyssal Nautilus", 1 },
                { "Subterranean Nautilus", 2 },
                { "AstroNautilus", 3 },
                { "Warden Nautilus", 4 },
                { "Worldbreaker Nautilus", 5 },
                { "Conqueror Nautilus", 6 },
            }},
            { "Neeko", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Winter Wonder Neeko", 1 },
                { "Star Guardian Neeko", 10 },
                { "Star Guardian Neeko Prestige Edition", 11 },
            }},
            { "Nidalee", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Snow Bunny Nidalee", 1 },
                { "Leopard Nidalee", 2 },
                { "French Maid Nidalee", 3 },
                { "Pharaoh Nidalee", 4 },
                { "Bewitching Nidalee", 5 },
                { "Headhunter Nidalee", 6 },
                { "Warring Kingdoms Nidalee", 7 },
                { "Challenger Nidalee", 8 },
                { "Super Galaxy Nidalee", 9 },
                { "Dawnbringer Nidalee", 11 },
            }},
            { "Nocturne", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Frozen Terror Nocturne", 1 },
                { "Void Nocturne", 2 },
                { "Ravager Nocturne", 3 },
                { "Haunting Nocturne", 4 },
                { "Eternum Nocturne", 5 },
                { "Cursed Revenant Nocturne", 6 },
                { "Elderwood Nocturne", 7 },
                { "Hextech Nocturne", 16 },
            }},
            { "Nunu", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sasquatch Nunu & Willump", 1 },
                { "Workshop Nunu & Willump", 2 },
                { "Grungy Nunu & Willump", 3 },
                { "Nunu & Willump Bot", 4 },
                { "Demolisher Nunu & Willump", 5 },
                { "TPA Nunu & Willump", 6 },
                { "Zombie Nunu & Willump", 7 },
                { "Papercraft Nunu & Willump", 8 },
            }},
            { "Olaf", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Forsaken Olaf", 1 },
                { "Glacial Olaf", 2 },
                { "Brolaf", 3 },
                { "Pentakill Olaf", 4 },
                { "Marauder Olaf", 5 },
                { "Butcher Olaf", 6 },
                { "SKT T1 Olaf", 15 },
                { "Dragonslayer Olaf", 16 },
            }},
            { "Orianna", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Gothic Orianna", 1 },
                { "Sewn Chaos Orianna", 2 },
                { "Bladecraft Orianna", 3 },
                { "TPA Orianna", 4 },
                { "Winter Wonder Orianna", 5 },
                { "Heartseeker Orianna", 6 },
                { "Dark Star Orianna", 7 },
                { "Victorious Orianna", 8 },
                { "Pool Party Orianna", 11 },
            }},
            { "Ornn", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Thunder Lord Ornn", 1 },
            }},
            { "Pantheon", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Myrmidon Pantheon", 1 },
                { "Ruthless Pantheon", 2 },
                { "Perseus Pantheon", 3 },
                { "Full Metal Pantheon", 4 },
                { "Glaive Warrior Pantheon", 5 },
                { "Dragonslayer Pantheon", 6 },
                { "Zombie Slayer Pantheon", 7 },
                { "Baker Pantheon", 8 },
                { "Pulsefire Pantheon", 16 },
            }},
            { "Poppy", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Noxus Poppy", 1 },
                { "Lollipoppy", 2 },
                { "Blacksmith Poppy", 3 },
                { "Ragdoll Poppy", 4 },
                { "Battle Regalia Poppy", 5 },
                { "Scarlet Hammer Poppy", 6 },
                { "Star Guardian Poppy", 7 },
                { "Snow Fawn Poppy", 14 },
                { "Hextech Poppy", 15 },
                { "Astronaut Poppy", 16 },
            }},
            { "Pyke", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sand Wraith Pyke", 1 },
                { "Blood Moon Pyke", 9 },
                { "PROJECT: Pyke", 16 },
                { "PsyOps Pyke", 25 },
            }},
            { "Qiyana", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Battle Boss Qiyana", 1 },
                { "True Damage Qiyana", 2 },
                { "True Damage Qiyana Prestige Edition", 10 },
            }},
            { "Quinn", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Phoenix Quinn", 1 },
                { "Woad Scout Quinn", 2 },
                { "Corsair Quinn", 3 },
                { "Heartseeker Quinn", 4 },
            }},
            { "Rakan", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Cosmic Dawn Rakan", 1 },
                { "Sweetheart Rakan", 2 },
                { "SSG Rakan", 3 },
                { "iG Rakan", 4 },
                { "Star Guardian Rakan", 5 },
            }},
            { "Rammus", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "King Rammus", 1 },
                { "Chrome Rammus", 2 },
                { "Molten Rammus", 3 },
                { "Freljord Rammus", 4 },
                { "Ninja Rammus", 5 },
                { "Full Metal Rammus", 6 },
                { "Guardian of the Sands Rammus", 7 },
                { "Sweeper Rammus", 8 },
                { "Hextech Rammus", 16 },
            }},
            { "RekSai", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Eternum Rek'Sai", 1 },
                { "Pool Party Rek'Sai", 2 },
                { "Blackfrost Rek'Sai", 9 },
            }},
            { "Renekton", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Galactic Renekton", 1 },
                { "Outback Renekton", 2 },
                { "Bloodfury Renekton", 3 },
                { "Rune Wars Renekton", 4 },
                { "Scorched Earth Renekton", 5 },
                { "Pool Party Renekton", 6 },
                { "Prehistoric Renekton", 7 },
                { "SKT T1 Renekton", 8 },
                { "Renektoy", 9 },
                { "Hextech Renekton", 17 },
                { "Blackfrost Renekton", 18 },
            }},
            { "Rengar", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Headhunter Rengar", 1 },
                { "Night Hunter Rengar", 2 },
                { "SSW Rengar", 3 },
                { "Mecha Rengar", 8 },
                { "Pretty Kitty Rengar", 15 },
                { "Guardian of the Sands Rengar", 23 },
            }},
            { "Riven", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Redeemed Riven", 1 },
                { "Crimson Elite Riven", 2 },
                { "Battle Bunny Riven", 3 },
                { "Championship Riven", 4 },
                { "Dragonblade Riven", 5 },
                { "Arcade Riven", 6 },
                { "Championship Riven 2016", 7 },
                { "Dawnbringer Riven", 16 },
                { "Pulsefire Riven", 18 },
                { "Valiant Sword Riven", 20 },
                { "Valiant Sword Riven Prestige Edition", 22 },
                { "Spirit Blossom Riven", 23 },
            }},
            { "Rumble", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Rumble in the Jungle", 1 },
                { "Bilgerat Rumble", 2 },
                { "Super Galaxy Rumble", 3 },
                { "Badlands Baron Rumble", 4 },
            }},
            { "Ryze", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Young Ryze", 1 },
                { "Tribal Ryze", 2 },
                { "Uncle Ryze", 3 },
                { "Triumphant Ryze", 4 },
                { "Professor Ryze", 5 },
                { "Zombie Ryze", 6 },
                { "Dark Crystal Ryze", 7 },
                { "Pirate Ryze", 8 },
                { "Ryze Whitebeard", 9 },
                { "SKT T1 Ryze", 10 },
                { "Championship Ryze", 11 },
                { "Guardian of the Sands Ryze", 13 },
            }},
            { "Samira", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "PsyOps Samira", 1 },
            }},
            { "Sejuani", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sabretusk Sejuani", 1 },
                { "Darkrider Sejuani", 2 },
                { "Traditional Sejuani", 3 },
                { "Bear Cavalry Sejuani", 4 },
                { "Poro Rider Sejuani", 5 },
                { "Beast Hunter Sejuani", 6 },
                { "Sejuani Dawnchaser", 7 },
                { "Firecracker Sejuani", 8 },
                { "Hextech Sejuani", 15 },
            }},
            { "Senna", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "True Damage Senna", 1 },
                { "True Damage Senna Prestige Edition", 9 },
                { "High Noon Senna", 10 },
            }},
            { "Sett", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Mecha Kingdoms Sett", 1 },
                { "Obsidian Dragon Sett", 8 },
                { "Obsidian Dragon Sett Prestige Edition", 9 },
            }},
            { "Shaco", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Mad Hatter Shaco", 1 },
                { "Royal Shaco", 2 },
                { "Nutcracko", 3 },
                { "Workshop Shaco", 4 },
                { "Asylum Shaco", 5 },
                { "Masked Shaco", 6 },
                { "Wild Card Shaco", 7 },
                { "Dark Star Shaco", 8 },
                { "Arcanist Shaco", 15 },
            }},
            { "Shen", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Frozen Shen", 1 },
                { "Yellow Jacket Shen", 2 },
                { "Surgeon Shen", 3 },
                { "Blood Moon Shen", 4 },
                { "Warlord Shen", 5 },
                { "TPA Shen", 6 },
                { "Pulsefire Shen", 15 },
                { "Infernal Shen", 16 },
                { "PsyOps Shen", 22 },
            }},
            { "Shyvana", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Ironscale Shyvana", 1 },
                { "Boneclaw Shyvana", 2 },
                { "Darkflame Shyvana", 3 },
                { "Ice Drake Shyvana", 4 },
                { "Championship Shyvana", 5 },
                { "Super Galaxy Shyvana", 6 },
            }},
            { "Singed", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Riot Squad Singed", 1 },
                { "Hextech Singed", 2 },
                { "Surfer Singed", 3 },
                { "Mad Scientist Singed", 4 },
                { "Augmented Singed", 5 },
                { "Snow Day Singed", 6 },
                { "SSW Singed", 7 },
                { "Black Scourge Singed", 8 },
                { "Beekeeper Singed", 9 },
            }},
            { "Sion", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Hextech Sion", 1 },
                { "Barbarian Sion", 2 },
                { "Lumberjack Sion", 3 },
                { "Warmonger Sion", 4 },
                { "Mecha Zero Sion", 5 },
                { "Worldbreaker Sion", 14 },
            }},
            { "Sivir", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Warrior Princess Sivir", 1 },
                { "Spectacular Sivir", 2 },
                { "Huntress Sivir", 3 },
                { "Bandit Sivir", 4 },
                { "PAX Sivir", 5 },
                { "Snowstorm Sivir", 6 },
                { "Warden Sivir", 7 },
                { "Victorious Sivir", 8 },
                { "Neo PAX Sivir", 9 },
                { "Pizza Delivery Sivir", 10 },
                { "Blood Moon Sivir", 16 },
                { "Odyssey Sivir", 25 },
            }},
            { "Skarner", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Sandscourge Skarner", 1 },
                { "Earthrune Skarner", 2 },
                { "Battlecast Alpha Skarner", 3 },
                { "Guardian of the Sands Skarner", 4 },
            }},
            { "Sona", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Muse Sona", 1 },
                { "Pentakill Sona", 2 },
                { "Silent Night Sona", 3 },
                { "Guqin Sona", 4 },
                { "Arcade Sona", 5 },
                { "DJ Sona", 6 },
                { "Sweetheart Sona", 7 },
                { "Odyssey Sona", 9 },
                { "PsyOps Sona", 17 },
            }},
            { "Soraka", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Dryad Soraka", 1 },
                { "Divine Soraka", 2 },
                { "Celestine Soraka", 3 },
                { "Reaper Soraka", 4 },
                { "Order of the Banana Soraka", 5 },
                { "Program Soraka", 6 },
                { "Star Guardian Soraka", 7 },
                { "Pajama Guardian Soraka", 8 },
                { "Winter Wonder Soraka", 9 },
                { "Dawnbringer Soraka", 15 },
                { "Nightbringer Soraka", 16 },
            }},
            { "Swain", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Northern Front Swain", 1 },
                { "Bilgewater Swain", 2 },
                { "Tyrant Swain", 3 },
                { "Dragon Master Swain", 4 },
                { "Hextech Swain", 11 },
            }},
            { "Sylas", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Lunar Wraith Sylas", 1 },
                { "Freljord Sylas", 8 },
            }},
            { "Syndra", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Justicar Syndra", 1 },
                { "Atlantean Syndra", 2 },
                { "Queen of Diamonds Syndra", 3 },
                { "Snow Day Syndra", 4 },
                { "SKT T1 Syndra", 5 },
                { "Star Guardian Syndra", 6 },
                { "Pool Party Syndra", 7 },
            }},
            { "TahmKench", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Master Chef Tahm Kench", 1 },
                { "Urf Kench", 2 },
                { "Coin Emperor Tahm Kench", 3 },
            }},
            { "Taliyah", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Freljord Taliyah", 1 },
                { "SSG Taliyah", 2 },
                { "Pool Party Taliyah", 3 },
            }},
            { "Talon", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Renegade Talon", 1 },
                { "Crimson Elite Talon", 2 },
                { "Dragonblade Talon", 3 },
                { "SSW Talon", 4 },
                { "Blood Moon Talon", 5 },
                { "Enduring Sword Talon", 12 },
                { "Talon Blackwood", 20 },
            }},
            { "Taric", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Emerald Taric", 1 },
                { "Armor of the Fifth Age Taric", 2 },
                { "Bloodstone Taric", 3 },
                { "Pool Party Taric", 4 },
                { "Taric Luminshield", 9 },
            }},
            { "Teemo", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Happy Elf Teemo", 1 },
                { "Recon Teemo", 2 },
                { "Badger Teemo", 3 },
                { "Astronaut Teemo", 4 },
                { "Cottontail Teemo", 5 },
                { "Super Teemo", 6 },
                { "Panda Teemo", 7 },
                { "Omega Squad Teemo", 8 },
                { "Little Devil Teemo", 14 },
                { "Beemo", 18 },
                { "Spirit Blossom Teemo", 25 },
                { "Spirit Blossom Teemo Prestige Edition", 27 },
            }},
            { "Thresh", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Deep Terror Thresh", 1 },
                { "Championship Thresh", 2 },
                { "Blood Moon Thresh", 3 },
                { "SSW Thresh", 4 },
                { "Dark Star Thresh", 5 },
                { "High Noon Thresh", 6 },
                { "Pulsefire Thresh", 13 },
                { "Pulsefire Thresh Prestige Edition", 14 },
                { "FPX Thresh", 15 },
                { "Spirit Blossom Thresh", 17 },
            }},
            { "Tristana", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Riot Girl Tristana", 1 },
                { "Earnest Elf Tristana", 2 },
                { "Firefighter Tristana", 3 },
                { "Guerilla Tristana", 4 },
                { "Buccaneer Tristana", 5 },
                { "Rocket Girl Tristana", 6 },
                { "Dragon Trainer Tristana", 10 },
                { "Bewitching Tristana", 11 },
                { "Omega Squad Tristana", 12 },
                { "Little Demon Tristana", 24 },
                { "Pengu Cosplay Tristana", 33 },
            }},
            { "Trundle", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Lil' Slugger Trundle", 1 },
                { "Junkyard Trundle", 2 },
                { "Traditional Trundle", 3 },
                { "Constable Trundle", 4 },
                { "Worldbreaker Trundle", 5 },
                { "Dragonslayer Trundle", 6 },
            }},
            { "Tryndamere", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Highland Tryndamere", 1 },
                { "King Tryndamere", 2 },
                { "Viking Tryndamere", 3 },
                { "Demonblade Tryndamere", 4 },
                { "Sultan Tryndamere", 5 },
                { "Warring Kingdoms Tryndamere", 6 },
                { "Nightmare Tryndamere", 7 },
                { "Beast Hunter Tryndamere", 8 },
                { "Chemtech Tryndamere", 9 },
                { "Blood Moon Tryndamere", 10 },
            }},
            { "TwistedFate", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "PAX Twisted Fate", 1 },
                { "Jack of Hearts Twisted Fate", 2 },
                { "The Magnificent Twisted Fate", 3 },
                { "Tango Twisted Fate", 4 },
                { "High Noon Twisted Fate", 5 },
                { "Musketeer Twisted Fate", 6 },
                { "Underworld Twisted Fate", 7 },
                { "Red Card Twisted Fate", 8 },
                { "Cutpurse Twisted Fate", 9 },
                { "Blood Moon Twisted Fate", 10 },
                { "Pulsefire Twisted Fate", 11 },
                { "Odyssey Twisted Fate", 13 },
            }},
            { "Twitch", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Kingpin Twitch", 1 },
                { "Whistler Village Twitch", 2 },
                { "Medieval Twitch", 3 },
                { "Crime City Twitch", 4 },
                { "Vandal Twitch", 5 },
                { "Pickpocket Twitch", 6 },
                { "SSW Twitch", 7 },
                { "Omega Squad Twitch", 8 },
                { "Ice King Twitch", 12 },
                { "Twitch Shadowfoot", 27 },
            }},
            { "Udyr", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Black Belt Udyr", 1 },
                { "Primal Udyr", 2 },
                { "Spirit Guard Udyr", 3 },
                { "Definitely Not Udyr", 4 },
                { "Dragon Oracle Udyr", 5 },
            }},
            { "Urgot", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Giant Enemy Crabgot", 1 },
                { "Butcher Urgot", 2 },
                { "Battlecast Urgot", 3 },
                { "High Noon Urgot", 9 },
                { "Pajama Guardian Cosplay Urgot", 15 },
            }},
            { "Varus", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Blight Crystal Varus", 1 },
                { "Arclight Varus", 2 },
                { "Arctic Ops Varus", 3 },
                { "Heartseeker Varus", 4 },
                { "Varus Swiftbolt", 5 },
                { "Dark Star Varus", 6 },
                { "Conqueror Varus", 7 },
                { "Infernal Varus", 9 },
            }},
            { "Vayne", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Vindicator Vayne", 1 },
                { "Aristocrat Vayne", 2 },
                { "Dragonslayer Vayne", 3 },
                { "Heartseeker Vayne", 4 },
                { "SKT T1 Vayne", 5 },
                { "Arclight Vayne", 6 },
                { "Soulstealer Vayne", 10 },
                { "PROJECT: Vayne", 11 },
                { "Firecracker Vayne", 12 },
                { "Firecracker Vayne Prestige Edition", 13 },
                { "Spirit Blossom Vayne", 14 },
                { "FPX Vayne", 15 },
            }},
            { "Veigar", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "White Mage Veigar", 1 },
                { "Curling Veigar", 2 },
                { "Veigar Greybeard", 3 },
                { "Leprechaun Veigar", 4 },
                { "Baron Von Veigar", 5 },
                { "Superb Villain Veigar", 6 },
                { "Bad Santa Veigar", 7 },
                { "Final Boss Veigar", 8 },
                { "Omega Squad Veigar", 9 },
                { "Elderwood Veigar", 13 },
                { "Furyhorn Cosplay Veigar", 23 },
            }},
            { "Velkoz", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Battlecast Vel'Koz", 1 },
                { "Arclight Vel'Koz", 2 },
                { "Definitely Not Vel'Koz", 3 },
                { "Infernal Vel'Koz", 4 },
            }},
            { "Vi", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Neon Strike Vi", 1 },
                { "Officer Vi", 2 },
                { "Debonair Vi", 3 },
                { "Demon Vi", 4 },
                { "Warring Kingdoms Vi", 5 },
                { "PROJECT: Vi", 11 },
                { "Heartbreaker Vi", 12 },
                { "PsyOps Vi", 20 },
            }},
            { "Viktor", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Full Machine Viktor", 1 },
                { "Prototype Viktor", 2 },
                { "Creator Viktor", 3 },
                { "Death Sworn Viktor", 4 },
                { "PsyOps Viktor", 5 },
            }},
            { "Vladimir", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Count Vladimir", 1 },
                { "Marquis Vladimir", 2 },
                { "Nosferatu Vladimir", 3 },
                { "Vandal Vladimir", 4 },
                { "Blood Lord Vladimir", 5 },
                { "Soulstealer Vladimir", 6 },
                { "Academy Vladimir", 7 },
                { "Dark Waters Vladimir", 8 },
                { "Nightbringer Vladimir", 14 },
            }},
            { "Volibear", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Thunder Lord Volibear", 1 },
                { "Northern Storm Volibear", 2 },
                { "Runeguard Volibear", 3 },
                { "Captain Volibear", 4 },
                { "El Rayo Volibear", 5 },
                { "The Thousand-Pierced Bear", 6 },
            }},
            { "Warwick", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Grey Warwick", 1 },
                { "Urf the Manatee", 2 },
                { "Big Bad Warwick", 3 },
                { "Tundra Hunter Warwick", 4 },
                { "Feral Warwick", 5 },
                { "Firefang Warwick", 6 },
                { "Hyena Warwick", 7 },
                { "Marauder Warwick", 8 },
                { "Urfwick", 9 },
                { "Lunar Guardian Warwick", 10 },
                { "PROJECT: Warwick", 16 },
            }},
            { "Xayah", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Cosmic Dusk Xayah", 1 },
                { "Sweetheart Xayah", 2 },
                { "SSG Xayah", 3 },
                { "Star Guardian Xayah", 4 },
            }},
            { "Xerath", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Runeborn Xerath", 1 },
                { "Battlecast Xerath", 2 },
                { "Scorched Earth Xerath", 3 },
                { "Guardian of the Sands Xerath", 4 },
                { "Dark Star Xerath", 5 },
            }},
            { "XinZhao", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Commando Xin Zhao", 1 },
                { "Imperial Xin Zhao", 2 },
                { "Viscero Xin Zhao", 3 },
                { "Winged Hussar Xin Zhao", 4 },
                { "Warring Kingdoms Xin Zhao", 5 },
                { "Secret Agent Xin Zhao", 6 },
                { "Dragonslayer Xin Zhao", 13 },
                { "Cosmic Defender Xin Zhao", 20 },
            }},
            { "Yasuo", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "High Noon Yasuo", 1 },
                { "PROJECT: Yasuo", 2 },
                { "Blood Moon Yasuo", 3 },
                { "Nightbringer Yasuo", 9 },
                { "Odyssey Yasuo", 10 },
                { "Battle Boss Yasuo", 17 },
                { "True Damage Yasuo", 18 },
                { "True Damage Yasuo Prestige Edition", 35 },
                { "Spirit Blossom Yasuo", 36 },
            }},
            { "Yone", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Spirit Blossom Yone", 1 },
            }},
            { "Yorick", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Undertaker Yorick", 1 },
                { "Pentakill Yorick", 2 },
                { "Arclight Yorick", 3 },
                { "Meowrick", 4 },
            }},
            { "Yuumi", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Battle Principal Yuumi", 1 },
                { "Heartseeker Yuumi", 11 },
            }},
            { "Zac", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Special Weapon Zac", 1 },
                { "Pool Party Zac", 2 },
                { "SKT T1 Zac", 6 },
            }},
            { "Zed", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Shockblade Zed", 1 },
                { "SKT T1 Zed", 2 },
                { "PROJECT: Zed", 3 },
                { "Championship Zed", 10 },
                { "Death Sworn Zed", 11 },
                { "Galaxy Slayer Zed", 13 },
                { "PsyOps Zed", 15 },
            }},
            { "Ziggs", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Mad Scientist Ziggs", 1 },
                { "Major Ziggs", 2 },
                { "Pool Party Ziggs", 3 },
                { "Snow Day Ziggs", 4 },
                { "Master Arcanist Ziggs", 5 },
                { "Battle Boss Ziggs", 6 },
                { "Odyssey Ziggs", 7 },
                { "Sugar Rush Ziggs", 14 },
                { "Hextech Ziggs", 23 },
            }},
            { "Zilean", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Old Saint Zilean", 1 },
                { "Groovy Zilean", 2 },
                { "Shurima Desert Zilean", 3 },
                { "Time Machine Zilean", 4 },
                { "Blood Moon Zilean", 5 },
                { "Sugar Rush Zilean", 6 },
            }},
            { "Zoe", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Cyber Pop Zoe", 1 },
                { "Pool Party Zoe", 2 },
                { "Star Guardian Zoe", 9 },
                { "Arcanist Zoe", 18 },
                { "Arcanist Zoe Prestige Edition", 19 },
            }},
            { "Zyra", new Dictionary<string, int> 
            {
                { "default", 0 },
                { "Wildfire Zyra", 1 },
                { "Haunted Zyra", 2 },
                { "SKT T1 Zyra", 3 },
                { "Dragon Sorceress Zyra", 4 },
                { "Coven Zyra", 5 },
                { "Coven Zyra Prestige Edition", 6 },
            }},
        };
    }
}
